% Peak Latency Simulation Helper Function: Simulate One Data Sample

% Purpose: This function simulates a trial-level (i.e., single-trial) ERP data 
% file for each subject in a sample. Then, all subjects' ERP files are concatenated 
% into one file and the peak latency for the electrode of interest (O2) and 
% time window (85-145 ms) is extracted for each subject and bin. Both trial-specific
% bins and condition-level bins are extracted.

% Notes:
% - Subjects are assigned to an attentional orienting speed group (High or Low) and
%   an age group (Younger or Older). These two group assignments determine a 
%   subject's intercept that is added to their peak latency. 

% ***See Section3_SimulatedData README.md available on the LME_MixedEffectsERPPeakLatency
% GitHub for pipeline details: https://github.com/basclab/LME_MixedEffectsERPPeakLatency/tree/main/Section3_SimulatedData

% Format:
    % simulateOneSample_forPeakLatency(sample, subjectN, saveFolder, leadField, sourceLocs, peakAmp, noiseProfileERPArray, subjectDataLog_oneSample)

% Inputs:
    % - sample: Sample ID for the current simulated sample (e.g., if sample = 1,
    %   the current sample will have an ID of #1).
    % - subjectN: Number of simulated subjects per sample.
    % - saveFolder: Folder for saving simulated data output files.
    %   This parent folder has the following subfolders: 01_P1PeakLatencyOutput_PreMerge
    %   and (optional) 01_ERPFiles (see Outputs section below). 
    % - leadField: Data structure created in LatencySim_03_SimulateERPData.m 
    %   for specifying the lead field, electrode montage, electrodes of interest, 
    %   and dipole orientation.
    % - sourceLocs: Index used to identify the dipole location from the
    %   leadField structure. This variable was created in
    %   LatencySim_03_SimulateERPData.m.
    % - peakAmp: Peak amplitude magnitude at dipole (values have been
    %   selected to produce the desired positive peak amplitude measured at
    %   electrode O2).
    % - noiseProfileERPArray: EEGLAB array of .erp files containing resting 
    %   state trials extracted from real participants. The epoch window length
    %   must be identical to the length of the simulated data in order to
    %   combine them together.
    % - subjectDataLog_oneSample: Table specifying each subject's assigned 
    %   attentional orienting speed/age group and condition-level bins after 
    %   inducing missing trials.
    
% Other Requirements:
    % - Needs MATLAB R2019a, EEGLAB v 2019_0, ERPLAB v 8.01, SEREEGA v 1.1.0
        % - For more information on EEGLAB, see: Delorme, A. & Makeig, S. (2004).
        %   EEGLAB: An open source toolbox for analysis of single-trial EEG dynamics
        %   including independent component analysis. https://sccn.ucsd.edu/eeglab/index.php
        % - For more information on ERPLAB, see: Lopez-Calderon, J., & Luck, S. J.
        %   (2014). ERPLAB: An open-source toolbox for the analysis of event-related
        %   potentials. https://erpinfo.org/erplab/    
        % - For more information on SEREEGA, see: Krol, L. R., Pawlitzki, J., Lotte, F.,
        %   Gramann, K., & Zander, T. O. (2018). SEREEGA: Simulating event-related EEG
        %   activity. https://github.com/lrkrol/SEREEGA
    % - Pediatric Head Atlas release v 1.1, Atlas 2 (4-8 years old) files
        % - Atlas files should be requested and downloaded from: https://www.pedeheadmod.net/pediatric-head-atlases/
        % - The folder containing the atlas files should then be added
        %   to the MATLAB path (via "Home" > "Set Path" > "Add with Subfolders").
    
% Function Steps:
    % 1. Specify output filenames and other variables
    % 2. Define simulation parameters
    % 3. Simulate each subject's ERP file
    % 4. Export this sample's peak latency output file
    % 5. (Optional) Export this sample's .erp file

% Outputs:
    % - Peak latency .txt files with one peak latency value per bin/
    %   electrode/subject. There is one file for each simulated sample.
    %   Each file contains the following columns:
        % - worklat: The peak latency for this simulated subject's
        %   specified bin and electrode. This value is extracted from a positive 
        %   peak from O2 (corresponding to E83 of the EGI HydroCel GSN 
        %   128-electrode montage) over a 85-145 ms time window.
        % - value: The peak amplitude for this simulated subject's specified
        %   bin and electrode. This value is extracted from a positive 
        %   peak from O2 (corresponding to E83 of the EGI HydroCel GSN 
        %   128-electrode montage) over a 85-145 ms time window.
        % - chindex: The electrode number (e.g., electrode #1 corresponds to 
        %   E83 in this simulation).
        % - chlabel: The label for this electrode (e.g., E83).
        % - bini: A number generated by ERPLAB when concatenating ERP
        %   data files across each sample's subjects. NOTE: This number
        %   is NOT used for subsequent processing. 
        % - binlabel: A label composed of [SUBJECTID]_:_[trial-specific bin label].
        %   The trial-specific bin label corresponds to the labels from the
        %   bin descriptor file (created in LatencySim_01_CreateBinDescriptorFile.m).
        %   The binlabel column is used to identify subject ID and stimuli-related  
        %   information in LatencySim_04_OrganizeDataFiles.R. 
        % - ERPset: This column is intentionally empty because it is NOT needed 
        %   for identifying subject ID (see binlabel column above). 
    % - (Optional) .erp files containing the trial-level waveforms for all
    %   subjects in a sample. There is one file for each simulated sample.
    %   These files are useful for visualizing waveforms or troubleshooting. 

% Usage Example:
    % >> sample = 1;
    % >> subjectN = 48;
    % >> saveFolder = 'C:\Users\basclab\Desktop\Section3_SimulatedData';
    % >> leadField   = lf_generate_frompha('4to8','128','labels',{'E70','E83'});
    % >> sourceLocs  = lf_get_source_nearest(leadField, [22 -76 5]);
    % >> leadField.orientation(sourceLocs,:) = [-0.08 -0.91 -0.40];
    % >> peakAmp = -32;
    % >> [tempERP noiseProfileERPArray] = pop_loaderp( 'filename', {'InfantNoise01.erp','InfantNoise02.erp','InfantNoise03.erp','InfantNoise04.erp','InfantNoise05.erp','InfantNoise06.erp','InfantNoise07.erp','InfantNoise08.erp','InfantNoise09.erp','InfantNoise10.erp'}, 'filepath', 'C:\Users\basclab\Desktop\Section3_SimulatedData\00_InfantNoiseRepository\');
    % >> subjectDataLog_oneSample = subjectDataLog(subjectDataLog.sample == sample,:);
    % >> simulateOneSample_forPeakLatency(sample, subjectN, saveFolder, leadField, sourceLocs, peakAmp, noiseProfileERPArray, subjectDataLog_oneSample);
    
% Copyright 2026 Serena K. Mon, Megan J. Heise, Lindsay C. Bowman
% Brain and Social Cognition Lab, University of California Davis, Davis, CA, USA.

% Permission is hereby granted, free of charge, to any person obtaining a 
% copy of this software and associated documentation files (the "Software"),
% to deal in the Software without restriction, including without limitation
% the rights to use, copy, modify, merge, publish, distribute, sublicense, 
% and/or sell copies of the Software, and to permit persons to whom the
% Software is furnished to do so, subject to the following conditions:

% The above copyright notice and this permission notice shall be included 
% in all copies or substantial portions of the Software.

% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.

function simulateOneSample_forPeakLatency(sample, subjectN, saveFolder, leadField, sourceLocs, peakAmp, noiseProfileERPArray, subjectDataLog_oneSample)
%% 1. SPECIFY OUTPUT FILENAMES AND OTHER VARIABLES

    % Specify filenames for output files: peak latency file and (optional) 
    % .erp file. The peak latency filename includes 'PreMerge' to signify 
    % that the file does not contain attentional orienting speed or age group
    % information yet (this information is added by the LatencySim_04_OrganizeDataFiles.R script). 
    saveSampleFilename = strcat('Sample', sprintf('%04d',sample)); % Format sample ID with leading zeros
    saveSamplePeakLatencyFilename = strcat(saveFolder, '\01_P1PeakLatencyOutput_PreMerge\', saveSampleFilename, '-P1PeakLatencyOutput_PreMerge.txt'); 
    saveSampleERPFilename = strcat(saveFolder, '\01_ERPFiles\', saveSampleFilename, '.erp');
    
    % Create ALLERP structure for storing all subjects' ERP files
    ALLERP = buildERPstruct([]);
    
    % Define variables for peak latency extraction: 
    % In this simulation, the P1 peak latency is extracted from a positive
    % peak over a 85-145 ms time window for O2 (electrode #1 in the ERP
    % file from the simulateOneSubject_forPeakLatency function). 
    timeWindowArray = [85 145];
    channelArray = [1];
    peakPolarity = 'positive'; 

%% 2. DEFINE SIMULATION PARAMETERS 

    % Define parameters for actor intercepts (in units of ms):
    % Each actor intercept is drawn from a normal distribution with one of
    % the following mean and standard deviation values (e.g., actor 01's 
    % normal distribution has a mean of -10 and standard deviation of 5;
    % actor 02's has a mean of -5 and standard deviation of 5, etc.).
    actorPeakLatencyArray = [-10, -5, 0, 5, 10]; % Peak latency population mean for each actor intercept distribution (one distribution per actor)
    actorPeakLatencySD = 5; % Peak latency population standard deviation for all actor intercept distributions 
    
    % Generate actor intercepts for this sample by randomly selecting one value
    % per actor. Each subject in this sample will have the same 5 actor intercepts.
    % These values are added to the subject's peak latency in the
    % simulateOneSubject_forPeakLatency function below.     
    sampleActorPeakLatencyArray = [normrnd(actorPeakLatencyArray(1),actorPeakLatencySD), normrnd(actorPeakLatencyArray(2),actorPeakLatencySD), ...
        normrnd(actorPeakLatencyArray(3),actorPeakLatencySD), normrnd(actorPeakLatencyArray(4),actorPeakLatencySD), ...
        normrnd(actorPeakLatencyArray(5),actorPeakLatencySD)];
    
    % Define parameters for attentional orienting speed/age group intercept:
    % - The subjectDataLog_oneSample variable specifies each subject's 
    %   assigned attentional orienting speed group (i.e., higOSpeed 
    %   or lowOSpeed) and age group (i.e., youngerAgeGroup or
    %   olderAgeGroup). 
    % - These group intercept values are constant for all simulated samples 
    %   (e.g., a subject in the lowOSpeed_olderAgeGroup in sample 1 will have 
    %   the same age intercept as a lowOSpeed_olderAgeGroup subject in sample 3). 
    % - Each subject's group intercept is added to their peak latency in 
    %   simulateOneSubject_forPeakLatency function below. 
    oSpeedAgeLabelArray = ["lowOSpeed_olderAgeGroup"; "higOSpeed_olderAgeGroup"; "lowOSpeed_youngerAgeGroup"; "higOSpeed_youngerAgeGroup"]; % Array of group labels
    peakLatencyArray = [115, 105, 125, 115]; % Peak latency group intercepts 
    
    % Assign a real noise file to subject. If there are more simulated subjects  
    % than noise files, multiple subjects may be assigned the same noise file 
    % but the trial-level pairing of simulated and real noise trials will 
    % differ across subjects due to randomization below.
    noiseFileN = length(noiseProfileERPArray);
    sampleNoiseNSubgroup = ceil(subjectN/noiseFileN); % Number of subjects assigned to each noise file (this number is rounded up if subjectN is not evenly divisible by the number of noise files)
    sampleNoiseIndexArray_original = repelem(1:noiseFileN, sampleNoiseNSubgroup); % Create noise filename array (NOTE: This array is not randomized yet and may have a length greater than subjectN)
    sampleNoiseIndexArray_random = datasample(sampleNoiseIndexArray_original, subjectN, 'Replace', false); % Extract randomized noise filename array of length subjectN 
    
%% 3. SIMULATE EACH SUBJECT'S ERP FILE

    for subject = 1:subjectN % Loop through each simulated subject
        subjectDataLog_oneSubject = subjectDataLog_oneSample(subjectDataLog_oneSample.SUBJECTID == subject,:); % Select this subject's row from subjectDataLog_oneSample
        
        subjectOSpeedAgeIndex = find(oSpeedAgeLabelArray == subjectDataLog_oneSubject.oSpeed_age); % Extract this subject's attentional orienting speed/age group
        samplePeakLatency_oneSubject = peakLatencyArray(subjectOSpeedAgeIndex); % Extract this subject's group intercept 
        
        subjectALLERP = buildERPstruct([]); % Create empty ALLERP structure to store subject's simulated ERP and real noise ERP
        subjectALLERP(1) = simulateOneSubject_forPeakLatency(samplePeakLatency_oneSubject, sampleActorPeakLatencyArray, leadField, sourceLocs, peakAmp); % Generate this subject's simulated ERP data file 
                          
        % Load this subject's assigned real noise file
        subjectALLERP(2) = noiseProfileERPArray(sampleNoiseIndexArray_random(subject));

        % Append the two ERP files
        subjectERP_append = pop_appenderp( subjectALLERP , 'Erpsets', [ 1 2]);
        % Extract simulated bin numbers
        binArray_simul = find(~contains(subjectERP_append.bindescr, 'Real noise'));
        binArray_noise = find(contains(subjectERP_append.bindescr, 'Real noise'));
        
        % Randomly sort binArray_noise
        binArray_noiseRandom = datasample(binArray_noise, length(binArray_noise), 'Replace', false);
        % Extract bin labels from simulated data file
        binLabelArray = subjectALLERP(1).bindescr;
        % Create bin equations with randomly paired simulated trials and
        % real noise trials
        subjectBinEquations = strcat("nb", string(binArray_simul), " = b", string(binArray_simul), " + b", string(binArray_noiseRandom), " label ", binLabelArray);
        % Add the randomly assigned noise trial to the corresponding
        % simulated trial using the bin equations
        subjectERP_withNoise = pop_binoperator( subjectERP_append, cellstr(subjectBinEquations));
        
        % Extract condition-level bins from subjectDataLog_oneSubject
        conditionBinEq = subjectDataLog_oneSubject{1,4:end}; 
        % Remove empty indices (i.e., subject was casewise deleted for a 
        % specific low trial-count percentage and does not have a condition-level
        % bin), otherwise ERPLAB will have an error
        conditionBinEq_Format = conditionBinEq(~cellfun('isempty',conditionBinEq));
        % Calculate mean-averaged waveform using condition-level bins
        subjectERP_final = pop_binoperator(subjectERP_withNoise, conditionBinEq_Format);        
        
        ALLERP(subject) = subjectERP_final; % Store this subject's final ERP file in the ALLERP structure         
    end

%% 4. EXPORT THIS SAMPLE'S PEAK LATENCY OUTPUT FILE

    % Concatenate all subjects' ERP data files into one ERP file
    ERP = pop_appenderp(ALLERP, 'Erpsets', [1:subjectN], 'Prefixes', cellstr(pad(string(1:subjectN), 2, 'left', '0')));
       
    % Calculate the peak latency for each bin over the time window and
    % electrodes specified above and save in .txt file
    ERP_peakLatency = pop_geterpvalues(ERP, timeWindowArray, [1:ERP.nbin], channelArray , ...
        'Baseline', 'pre', 'Binlabel', 'on', 'FileFormat', 'long', ...
        'Filename', saveSamplePeakLatencyFilename, 'Fracreplace', 'NaN', 'IncludeLat', 'yes', ...
        'InterpFactor',  1, 'Measure', 'peakampbl', 'Neighborhood', 3, 'PeakOnset',  1, ...
        'Peakpolarity', peakPolarity, 'Peakreplace', 'absolute', 'Resolution',  3);
    
%% 5. (OPTIONAL) EXPORT THIS SAMPLE'S .ERP FILE
    
    % Uncomment the line below to save the concatenated .erp file containing
    % all subjects' trial-level and condition-level waveforms    
    %ERP = pop_savemyerp(ERP, 'erpname', saveSampleERPFilename, 'filename', saveSampleERPFilename, 'filepath', saveFolder);

end